export const ROLE_DELETE_PENDING = 'ROLE_DELETE_PENDING';
export const ROLE_DELETE_FULFILLED = 'ROLE_DELETE_FULFILLED';
export const ROLE_DELETE_REJECTED = 'ROLE_DELETE_REJECTED';
export const PAGINATION_CHANGE_PAGE = 'PAGINATION_CHANGE_PAGE';
export const PAGINATION_CHANGE_RESULTPERPAGE = 'PAGINATION_CHANGE_RESULTPERPAGE';