export const USERLIST_FETCH_PENDING = 'USERLIST_FETCH_PENDING';
export const USERLIST_FETCH_FULFILLED = 'USERLIST_FETCH_FULFILLED';
export const USERLIST_FETCH_REJECTED = 'USERLIST_FETCH_REJECTED';
export const PAGINATION_CHANGE_PAGE = 'PAGINATION_CHANGE_PAGE';
export const PAGINATION_CHANGE_RESULTPERPAGE = 'PAGINATION_CHANGE_RESULTPERPAGE';